### ISSUE TITLE
The tracker doesn't keep content alive

### ISSUE THREAD

**Issue by SteJW** [thoughtco/statamic-cache-tracker#13]
Hi,
Thanks for this addon! It's working great, but only for the first page load!

I have cache half enabled and when I run a page once, I save an used entry from that page, and I refresh the page. That works great and as expected.
When I reload the page a couple of times and I save an used entry on that page, it doesn't invalidate the page. It looks like the cache is being reloaded with a lesser list of connected entries.

I did a var_dump of the content that's being saved in the CacheTracker.php on line 57.
```
if ($this->content) {
            var_dump($this->content);
            Tracker::add($url, array_unique($this->content));
        }
```

It lists this, and more:
```
Array
--
  | (
  | [0] => pages:16653e3d-01e5-4a55-91b7-6b0e8d3d7be9
  | [1] => partial:_components/widgets
  | [2] => partial:_components/page_builder/widget_banner/widget_banner
  | [3] => banners:987d0ff6-caea-444b-8c01-933b78eeec00
  | [4] => banners:987d0ff6-caea-444b-8c01-933b78eeec00
  | [5] => events:441cc017-d640-439d-9f86-f51ff91123dd
  | [6] => things_to_do:8bc736e5-e020-43c4-8239-a773395e8abf
  | [7] => events:441cc017-d640-439d-9f86-f51ff91123dd
  | [8] => things_to_do:8bc736e5-e020-43c4-8239-a773395e8abf
  | [9] => events:441cc017-d640-439d-9f86-f51ff91123dd
  | [10] => things_to_do:8bc736e5-e020-43c4-8239-a773395e8abf
  | [11] => events:441cc017-d640-439d-9f86-f51ff91123dd
  | [12] => things_to_do:8bc736e5-e020-43c4-8239-a773395e8abf
  | [13] => events:441cc017-d640-439d-9f86-f51ff91123dd
  | [14] => things_to_do:8bc736e5-e020-43c4-8239-a773395e8abf
  | [15] => things_to_do:8bc736e5-e020-43c4-8239-a773395e8abf
  | [16] => events:441cc017-d640-439d-9f86-f51ff91123dd
  | [17] => asset:assets::things-to-do/dsc04903.jpg
  | [18] => asset:assets::things-to-do/dsc04903.jpg
  | [19] => global:events
```

When I reload I get this:
```
  | Array
-- | --
  | (
  | [0] => pages:16653e3d-01e5-4a55-91b7-6b0e8d3d7be9
  | [1] => form:create
  | [2] => partial:_layout/footer/_newsletter_form
  | )
```

**Comment by ryanmitchell** [comment]
As you said as the middleware still runs on subsequent page loads it’s overwriting the manifest for that page. You could maybe look to merge the manifests on page load or not run it if the manifest for that url exists.

It’s not something I will look into as we don’t ever have a use for half cache but I’ll happily review a PR that supports it if you want to work on it.
