### ISSUE TITLE
Cache not cleared on entry create when using entry query

### ISSUE THREAD

**Issue by stuartcusackie** [thoughtco/statamic-cache-tracker#3]
I'm not sure if this package is intended to cover this particular situation, but let me explain anyway...

I have an `events-index.blade.php` template for an entry in my 'pages' collection. In this template I find all entries in my 'events' collection using the Entry facade, e.g.

```
$events = Entry::query()
            ->where('collection', 'events')
            ->where('published', true)
            ->get();
```

These events are then output in my template like so (blade components):

```
@foreach($events as $event)
  <x-event-listing :event="$event" />
@endforeach
```

I was hoping that this package would clear the static cache for this 'pages' entry when I create a new entry in the 'events' collection, but it doesn't seem to.

Is this intended behaviour or do I need to use `addAdditionalTracker()`, or should I just stick to the rules in `config/static_caching.php` for this kind of stuff?

Thanks!

**Comment by ryanmitchell** [comment]
Are you including that using a partial tag? If so you could clear it using a listener:

```php
Tracker::invalidate('partial:events-index');
```

**Comment by stuartcusackie** [comment]
I'm not using Antlers and very few tags. My project is all Blade.  Here's a simplified version:

```
@php
$events = Entry::query()
            ->where('collection', 'events')
            ->where('published', true)
            ->get();
@endphp

<x-layout >
  @foreach($upcomingEvents as $event)
    <x-event-listing :event="$event" />
  @endforeach
</x-layout>
```

Sounds like this package relies on Antlers?

**Comment by ryanmitchell** [comment]
It relies on augmentation, not necessarily Antlers. If your entries are being augmented inside your blade component then they should be being picked up and tracked.

You can dump the contents of the cache store to see whats been tracked if you want:

```php
dd(\Thoughtco\StatamicCacheTracker\Facades\Tracker::cacheStore()->get('tracker::urls'));
```

**Comment by stuartcusackie** [comment]
Forgive my ignorance sir, but where should I add this?

I have placed the dump at the bottom of my Blade template and it just returns `null`.

**Comment by stuartcusackie** [comment]
I see I see. I'll try that in future if I need something more sophisticated. For the moment I think the default static caching rules along with your package will handle my current needs. Thank you.
